# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: true
os:
  - linux
  
before_install:
  sudo apt-get update &
  sudo apt-get install libgit2-dev

after_success:
    - Rscript -e 'covr::coveralls()'
